version: '3.8'

services:
  backend:
    build:
      context: ./BackOffice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/ebook-db
    depends_on:
      - mongo

  frontend:
    build:
      context: ./FrontOffice
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: